spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CustomerService
          uri: http://localhost:8080
          predicates:
            - Path=/customers/**
        - id: TransactionService
          uri: http://localhost:8081
          predicates:
            - Path=/transactions/**


eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

#springdoc:
#  swagger-ui:
##    path: /swagger-ui.html
#    urls:
#      - name: Customer Service
#        url: /aggregate/customer-service/v3/api-docs
#      - name: Transaction Service
#        url: /aggregate/transaction-service/v3/api-docs
#  api-docs:
#    path: /api-docs