server:
  port: 8081
spring:
  application:
    name: TransactionService
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

customer:
  url: http://localhost:8080/customers
#  url: http://localhost:8222/customers
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
