server:
  port: 8080
spring:
  application:
    name: TransactionService
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

customer:
  url: http://localhost:8081